version: "3.4"

services:
  gestaoavaliacao.rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=sme@serap
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - sme-serap-worker.env
    networks:
      - default

networks:
  default:
    driver: bridge
